# Generated by Django 4.0.3 on 2022-03-03 17:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('board', '0003_anonypost_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='freecomment',
            name='author',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='freecomment_author', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='freecomment',
            name='post',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='freecomment_post', to='board.freepost'),
        ),
    ]
