# Generated by Django 4.0.3 on 2022-03-05 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0004_freecomment_author_alter_freecomment_post'),
    ]

    operations = [
        migrations.AddField(
            model_name='anonypost',
            name='anony',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='freepost',
            name='anony',
            field=models.BooleanField(default=False),
        ),
    ]
