# Generated by Django 4.0.3 on 2022-03-08 01:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0006_anonycomment_author'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='anonycomment',
            options={'ordering': ['-date']},
        ),
    ]
