# Generated by Django 4.0.3 on 2022-03-08 02:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0008_profile'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
