# Generated by Django 4.0.3 on 2022-03-08 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0010_profile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='username',
        ),
        migrations.AddField(
            model_name='anonypost',
            name='like_count',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
