# Generated by Django 4.0.3 on 2022-03-08 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0011_remove_profile_username_anonypost_like_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='like_posts',
            field=models.ManyToManyField(blank=True, related_name='like_users', to='board.anonypost'),
        ),
    ]
