# Generated by Django 4.0.3 on 2022-03-08 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0012_profile_like_posts'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='like_posts',
        ),
        migrations.AddField(
            model_name='profile',
            name='like_anonyposts',
            field=models.ManyToManyField(blank=True, related_name='like_anonyposts', to='board.anonypost'),
        ),
        migrations.AddField(
            model_name='profile',
            name='like_freeposts',
            field=models.ManyToManyField(blank=True, related_name='like_freeposts', to='board.freepost'),
        ),
    ]
