# Generated by Django 4.0.3 on 2022-03-14 12:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0014_freepost_like_count'),
    ]

    operations = [
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='images/')),
                ('anonypost', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='anonypost_image', to='board.anonypost')),
                ('freepost', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='freepost_image', to='board.freepost')),
            ],
        ),
    ]
