# Generated by Django 4.0.3 on 2022-03-14 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0015_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='anonypost',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
        migrations.AddField(
            model_name='freepost',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
        migrations.DeleteModel(
            name='Photo',
        ),
    ]
